import Person from 'models/person'
import { ValidationError } from 'objection'
import testDatabaseConnection from 'tests/utils/test-database-connection'

beforeAll(async () => {
  await testDatabaseConnection.initDatabase()
})

beforeEach(async () => {
  await testDatabaseConnection.cleanDatabase()
})

afterAll(async () => {
  await testDatabaseConnection.destroyDatabase()
})

describe('person insert', () => {
  it('successfully inserts', async () => {
    const person = await Person.query().insertGraph({
      name: 'Brandon',
    })

    expect(person.id).toBeTruthy()
  })
  it('rejects person with empty name', async () => {
    await expect(
      Person.query().insertGraph({
        name: '',
      })
    ).rejects.toThrow(ValidationError)
  })
})
